apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://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@github.com/cetearyl/argocd.git 
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
